# Generated by Django 3.0.7 on 2020-06-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.CharField(max_length=200)),
                ('orderId', models.CharField(max_length=200, unique=True)),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Don hang',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Item ID')),
                ('position', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('order_Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.OrderForm')),
            ],
            options={
                'verbose_name_plural': 'Item',
            },
        ),
    ]
